// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI Chatbot Assistant flow for providing math help.
 *
 * - aiChatbotAssistant - A function that provides math assistance using an AI chatbot.
 * - AiChatbotAssistantInput - The input type for the aiChatbotAssistant function.
 * - AiChatbotAssistantOutput - The return type for the aiChatbotAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiChatbotAssistantInputSchema = z.object({
  question: z.string().describe('The math question the student needs help with.'),
  studentGrade: z.number().describe('The grade level of the student.'),
  topic: z.string().describe('The math topic the question relates to.'),
});

export type AiChatbotAssistantInput = z.infer<typeof AiChatbotAssistantInputSchema>;

const AiChatbotAssistantOutputSchema = z.object({
  answer: z.string().describe('The AI chatbot assistant answer to the question, with step-by-step explanations, follow-up questions, and suggestions for interactive diagrams.'),
});

export type AiChatbotAssistantOutput = z.infer<typeof AiChatbotAssistantOutputSchema>;

export async function aiChatbotAssistant(input: AiChatbotAssistantInput): Promise<AiChatbotAssistantOutput> {
  return aiChatbotAssistantFlow(input);
}

const aiChatbotAssistantPrompt = ai.definePrompt({
  name: 'aiChatbotAssistantPrompt',
  input: {schema: AiChatbotAssistantInputSchema},
  output: {schema: AiChatbotAssistantOutputSchema},
  prompt: `You are a friendly and helpful AI math tutor. Your goal is to help students understand math concepts and solve problems.

  The student is in grade {{studentGrade}} and is asking a question about {{topic}}.

  Student's Question: {{{question}}}

  Provide a structured explanation that includes:
  * Step-by-step solutions
  * Multiple solving methods if applicable
  * Real-life context examples to illustrate the concept
  * Follow-up questions to test understanding
  * Suggestions for interactive diagrams to visualize the problem
  * A link to a relevant, working, high-quality YouTube video from Khan Academy that provides a visual explanation of the concept. If a suitable video from Khan Academy cannot be found, do not include a link.

  Make sure your response is easy to understand and encourages the student to learn.
  Format your answer to include all the elements listed above.
  `,
});

const aiChatbotAssistantFlow = ai.defineFlow(
  {
    name: 'aiChatbotAssistantFlow',
    inputSchema: AiChatbotAssistantInputSchema,
    outputSchema: AiChatbotAssistantOutputSchema,
  },
  async (input) => {
    try {
      const {output} = await aiChatbotAssistantPrompt(input);
      return output!;
    } catch (error) {
      console.error('AI Chatbot Assistant Error:', error);
      // Return a user-friendly error message within the expected schema.
      return {
        answer: "I'm sorry, I'm currently experiencing high demand and can't provide a response right now. Please try again in a few moments."
      };
    }
  }
);
